classdef PointCloud < robotics.ros.Message
    %PointCloud MATLAB implementation of sensor_msgs/PointCloud
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2016 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'sensor_msgs/PointCloud' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'd8e9c3f5afbdd8a130fd1d2763945fca' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        GeometryMsgsPoint32Class = robotics.ros.msg.internal.MessageFactory.getClassForType('geometry_msgs/Point32') % Dispatch to MATLAB class for message type geometry_msgs/Point32
        SensorMsgsChannelFloat32Class = robotics.ros.msg.internal.MessageFactory.getClassForType('sensor_msgs/ChannelFloat32') % Dispatch to MATLAB class for message type sensor_msgs/ChannelFloat32
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        Points
        Channels
    end
    
    
    
    properties (Access = protected)
        Cache = struct('Header', [], 'Points', [], 'Channels', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Channels', 'Header', 'Points'} % List of non-constant message properties
        ROSPropertyList = {'channels', 'header', 'points'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = PointCloud(msg)
            %PointCloud Construct the message object PointCloud
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'PointCloud', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function points = get.Points(obj)
            %get.Points Get the value for property Points
            if isempty(obj.Cache.Points)
                javaArray = obj.JavaMessage.getPoints;
                array = obj.readJavaArray(javaArray, obj.GeometryMsgsPoint32Class);
                obj.Cache.Points = feval(obj.GeometryMsgsPoint32Class, array);
            end
            points = obj.Cache.Points;
        end
        
        function set.Points(obj, points)
            %set.Points Set the value for property Points
            if ~isvector(points) && isempty(points)
                % Allow empty [] input
                points = feval([obj.GeometryMsgsPoint32Class '.empty'], 0, 1);
            end
            
            validateattributes(points, {obj.GeometryMsgsPoint32Class}, {'vector'}, 'PointCloud', 'Points');
            
            javaArray = obj.JavaMessage.getPoints;
            array = obj.writeJavaArray(points, javaArray, obj.GeometryMsgsPoint32Class);
            obj.JavaMessage.setPoints(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Points)
                obj.Cache.Points = [];
                obj.Cache.Points = obj.Points;
            end
        end
        
        function channels = get.Channels(obj)
            %get.Channels Get the value for property Channels
            if isempty(obj.Cache.Channels)
                javaArray = obj.JavaMessage.getChannels;
                array = obj.readJavaArray(javaArray, obj.SensorMsgsChannelFloat32Class);
                obj.Cache.Channels = feval(obj.SensorMsgsChannelFloat32Class, array);
            end
            channels = obj.Cache.Channels;
        end
        
        function set.Channels(obj, channels)
            %set.Channels Set the value for property Channels
            if ~isvector(channels) && isempty(channels)
                % Allow empty [] input
                channels = feval([obj.SensorMsgsChannelFloat32Class '.empty'], 0, 1);
            end
            
            validateattributes(channels, {obj.SensorMsgsChannelFloat32Class}, {'vector'}, 'PointCloud', 'Channels');
            
            javaArray = obj.JavaMessage.getChannels;
            array = obj.writeJavaArray(channels, javaArray, obj.SensorMsgsChannelFloat32Class);
            obj.JavaMessage.setChannels(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Channels)
                obj.Cache.Channels = [];
                obj.Cache.Channels = obj.Channels;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
            obj.Cache.Points = [];
            obj.Cache.Channels = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
            cpObj.Points = copy(obj.Points);
            cpObj.Channels = copy(obj.Channels);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
            PointsCell = arrayfun(@(x) feval([obj.GeometryMsgsPoint32Class '.loadobj'], x), strObj.Points, 'UniformOutput', false);
            obj.Points = vertcat(PointsCell{:});
            ChannelsCell = arrayfun(@(x) feval([obj.SensorMsgsChannelFloat32Class '.loadobj'], x), strObj.Channels, 'UniformOutput', false);
            obj.Channels = vertcat(ChannelsCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Header = saveobj(obj.Header);
            strObj.Points = arrayfun(@(x) saveobj(x), obj.Points);
            strObj.Channels = arrayfun(@(x) saveobj(x), obj.Channels);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.msggen.sensor_msgs.PointCloud.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.msggen.sensor_msgs.PointCloud;
            obj.reload(strObj);
        end
    end
end
